### ISSUE TITLE
Incorrect handling of tcp.

### ISSUE THREAD

**Issue by yihuang** [postgres-haskell/postgres-wire#26]
I was trying to build a postgres protocol compatible server application on top of ``postgres-wire``, but I found that the decoder implementation is not streamlined.
For example, here(https://github.com/postgres-haskell/postgres-wire/blob/master/src/Database/PostgreSQL/Driver/Connection.hs#L174) you need to hard code the length of the buffer, and this code is actually problematic because it might only receive an arbitrary length of data.

**Comment by qnikst** [comment]
It seems to me that the observation is not quite correct, see how that work:
1. https://github.com/postgres-haskell/postgres-wire/blob/master/src/Database/PostgreSQL/Driver/Connection.hs#L174 we pass action `rReceive rawConn bs 1024` - a receive next chunk action to `parseParameters`.
2. `rReceive` is wrapper over [rawReceive](https://github.com/postgres-haskell/postgres-wire/blob/master/src/Database/PostgreSQL/Driver/RawConnection.hs#L90-L99)  that reads up `n` (1024 in this case) bytes and prepends `bs` to the value read.
3. `parseParameters` calls to [decodeServerMessage](https://github.com/postgres-haskell/postgres-wire/blob/master/src/Database/PostgreSQL/Driver/Connection.hs#L245) and passes readAction.
4.  [decodeServerMessage](https://github.com/postgres-haskell/postgres-wire/blob/master/src/Database/PostgreSQL/Protocol/Decoders.hs#L22-L41) first parses header, gets required number of bytes to read and reads them using callback.

So this protocol can read unknown in advance size of data. Unfortunately current implementation is does `N` copies where `N` is number of times driver needs to read the data, that may be suboptimal on the long messages.

Does this explanation makes sense to you? Or have I missed anything?

**Comment by yihuang** [comment]
Oh, it seems correct. I guess I was taking ‘rawReceive’ as OS’s recv before.
